# Generated by Django 2.2.6 on 2019-11-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mikao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='treatments',
            field=models.ManyToManyField(to='mikao.Treatment', verbose_name='list of treatments'),
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mikao.User'),
        ),
    ]
