# Generated by Django 2.2.6 on 2019-12-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='treatments',
            field=models.ManyToManyField(to='mikao.Treatment'),
        ),
    ]
